language: ruby
rvm:
  - 2.6.5
gemfile:
  - travis/gemfiles/5.2.gemfile
  - travis/gemfiles/6.0.gemfile
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'CREATE DATABASE enum_kit_test;' -U postgres
env:
  global:
    - DATABASE_URL="postgresql://127.0.0.1:5432/enum_kit_test"
    - RSPEC_DEFAULT_FORMATTER=doc
